#!/bin/bash

if [ -z $HTTP_USERNAME ]; then
  HTTP_USERNAME="flower"
fi

if [ -z $HTTP_PASSWORD ]; then
  HTTP_PASSWORD="insecure"
fi

/usr/bin/htpasswd -bc /flower/htpasswd $HTTP_USERNAME $HTTP_PASSWORD
